# Generated by Django 2.0.2 on 2020-05-27 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='例如:抖音-记录美好生活', max_length=100)),
                ('introduction', models.CharField(default='在这里写app描述', max_length=256)),
                ('link', models.CharField(default='例如:https://www.baidu.com', max_length=100)),
                ('icon', models.ImageField(default='default_icon.jpg', upload_to='images')),
                ('image', models.ImageField(default='default_pic.png', upload_to='images')),
                ('votes', models.IntegerField(default=0)),
                ('pub_date', models.DateField()),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
